# Generated by Django 5.0.7 on 2024-11-05 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choco_app', '0002_flavor_description_suggestion_customer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flavor',
            name='description',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='customer_name',
        ),
    ]
